# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [shaq, penny]
patreon: # Replace with a single Patreon username http://threadup.com
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username tony
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel 
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username Tina 
issuehunt: # Replace with a single IssueHunt username flipper
otechie: # Replace with a single Otechie username E3
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://lowkeyquiz.com/quiz/2nd-grade/?utm_source=c524f8875df342cabb29d04523950286%3A%20Tornado.io%21&utm_medium=cpm&utm_campaign=felt3rso-x1us2iox&utm_content=50292', 'https://forhims.com','https://Tyson.com','https://crest.com','https://magnoliaelectricpower.com','https://ironsource.mobi','https://who.int']
